from chimera import runCommand
runCommand('help atomspec')
runCommand('select :.b')
runCommand('select ::b')
runCommand('help select')
runCommand('select atom-spec')
runCommand('preset apply interactive 1')
runCommand('focus #0')
runCommand('hide :hoh')
runCommand('delete :hoh')
runCommand('turn x 90')
runCommand('select hem')
runCommand('select :hem')
runCommand('select :.b hem')
runCommand('select hem')
runCommand('select :hem')
runCommand('select :h.b')
runCommand('select :.b')
runCommand('select :hem 147.b')
runCommand('select :hem 147.b cmd')
runCommand('~select')
runCommand('findclash #0:.b test #0:.c overlapCutoff -0.4 hbondAllowance 0.0 reveal true colorClashes true clashcolor yellow')
runCommand('~findclash')
runCommand('findclash #0:hem test #0:hem overlapCutoff -0.4 hbondAllowance 0.0 reveal true colorClashes true clashcolor pink ')
runCommand('findclash #0:hem test #0:hem overlapCutoff -0.4 hbondAllowance 0.0 reveal true colorClashes true clashcolor purple')
runCommand('findclash #0:hem test #0:hem overlapCutoff -0.4 hbondAllowance 0.0 reveal true colorClashes true clashcolor pink ')
runCommand('select :hem')
runCommand('select :hem.B')
runCommand('select :hem.B & za<0.4')
runCommand('select :hem.B')
runCommand('za<0.4')
runCommand('select :hem.B')
